### ISSUE TITLE
use the right width

### ISSUE THREAD

**Issue by klanyi** [plone/plone.outputfilters#12]
Hi, in some cases (i.e. in case of using collective.ckeditor = 3.6.12) the code for an image looks like this:
`<img alt="..." class="captioned" wdth="315" height="..." src="..." style="width:50%;" />`
Your filter should use the width term in the style attribute. Would it be possible?
Katrin

**Comment by MrTango** [comment]
By default that's not done, but one can register an output filter, in an add-on to archive this.
In Plone 6 we are empowering the outputfilter a bit more, all features like the srcset support can be easily used by other editors as ckeditor as well.
