### ISSUE TITLE
resolveuid filter does not work with Products.PortalTransforms 3.0.0

### ISSUE THREAD

**Issue by michaeldunstan** [plone/plone.outputfilters#23]
Create a page in Plone 5.1b3 and embed an image. The image is visible while editing the page. But disappears when viewing the page.

While editing the page the source for the img tag is of the form:

`<p><img class="image-inline" src="resolveuid/f7c0f5b0af0c422b92bb07c82c0a2a9e/@@images/image/large" alt="" data-linktype="image" data-scale="large" data-val="f7c0f5b0af0c422b92bb07c82c0a2a9e" /></p>`

And when viewing the page the source the img tag is stripped. All that is remains is:

`<p></p>`

Products.PortalTransforms 3.0.0 updated the safe HTML transform to use lxml.html.Cleaner. See https://github.com/plone/Products.PortalTransforms/blob/master/CHANGES.rst

Pinning to Products.PortalTransforms = 2.2.2 immediately restores view of the images.

**Comment by petschki** [comment]
is this still an issue in Plone 5.1.4 ?

**Comment by petschki** [comment]
I'll close this as this was fixed. Products.PortalTransforms version for Plone `5.1-latest` is `3.1.5` ... if still an issue please reopen
