### ISSUE TITLE
resolveuid_and_caption needs to be ported to python3

### ISSUE THREAD

**Issue by pbauer** [plone/plone.outputfilters#27]
It is based on sgmllib which in gone in py3. We need to check if it is still of any use (I have not used it in a while) and then maybe port it to use BS4.

**Comment by pbauer** [comment]
I just now saw that @tobiasherp started work on this in https://github.com/plone/plone.outputfilters/compare/python3-therp 
@MrTango did you look at that when you started working on it? It seems not finished at all, in fact there are some syntax-errors.

**Comment by petschki** [comment]
@tobiasherp I've started finishing your branch using `bs4`. My first try to use `lxml` only wasn't successful because of parsing just "tag soups" (as mentioned here https://lxml.de/lxmlhtml.html#parsing-html-fragments) ... right now, there are 2 tests failing, one regarding "linked captioned images" and one regarding unicode conversions. I'll try to tackle them down today...

**Comment by pbauer** [comment]
I'm trying this branch in https://jenkins.plone.org/view/PLIPs/job/plip-py3/563/
@petschki: did you check that the tests are passing in py2?

**Comment by petschki** [comment]
at least py3 p.outputfilter.tests are all green now (https://jenkins.plone.org/view/PLIPs/job/plip-py3/564/testReport/plone.outputfilters.tests.test_resolveuid_and_caption/) ... still fighting with py2/py3 doctest differences ... 🤯

**Comment by petschki** [comment]
@pbauer well ... I'm obviously not a rebasing chef, so sorry for the noise in the commits ... but now everything is ready in python3 branch. Changes from @tomgross regarding resolving absolute links are backported and the tests are green now (on py2.7 and py3.6) ... if there's anything I can check or improve (stash some commits?) let me know ...

**Comment by petschki** [comment]
sgmllib has been removed in 3.1.0 ... I'll close this
