### ISSUE TITLE
Image caption support in Plone 5.1.x

### ISSUE THREAD

**Issue by tuticapi** [plone/plone.outputfilters#37]
- Change the image caption template to use  &lt;figure&gt; and &lt;figcaption&gt;

- Add an ImageCaptioningEnabler utility which can be enabled via the portal registry setting plone.image_captioning.

Ref:
https://github.com/plone/plone.app.upgrade/issues/231
https://github.com/plone/mockup/issues/977
https://github.com/plone/Products.CMFPlone/issues/3098

**Comment by vincentfretin** [comment]
Image caption feature is available in Plone 5.2.2.
